/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ICard: (typeof import('./src/components/ICard/ICard.vue'))['default']
    ICharts: (typeof import('./src/components/ICharts/ICharts.vue'))['default']
    Icon: (typeof import('./src/components/Icon/Icon.vue'))['default']
    IDiffEditor: (typeof import('./src/components/IDiffEditor/IDiffEditor.vue'))['default']
    IEditor: (typeof import('./src/components/IEditor/IEditor.vue'))['default']
    ILocationSelector: (typeof import('./src/components/ILocationSelector/ILocationSelector.vue'))['default']
    IPageHeader: (typeof import('./src/components/IPageHeader/IPageHeader.vue'))['default']
    ITable: (typeof import('./src/components/ITable/ITable.vue'))['default']
    JobCard: (typeof import('./src/components/JobCard/JobCard.vue'))['default']
    JobSearch: (typeof import('./src/components/JobSearch/JobSearch.vue'))['default']
    KnowledgeGraph: (typeof import('./src/components/KnowledgeGraph/KnowledgeGraph.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
